module.exports = {
  content: ['*.html', '_site/*.html','_site/**/*.html', '_pages/**/*.md', '_posts/**/*.md', '_layouts/**/*.html', '_includes/**/*.html'],
  theme: {
    screens: {
      sm: '580px',
      md: '760px',
      lg: '940px',
      xl: '1180px',
    },
    fontSize: {
      '3xs': ['0.75rem', { lineHeight: '1rem' }],
      '2xs': ['0.8125rem', { lineHeight: '1rem' }],
      xs: ['0.875rem', { lineHeight: '1rem' }],
      sm: ['0.9375rem', { lineHeight: '1.25rem' }],
      base: ['1rem', { lineHeight: '1.5rem' }],
      lg: ['1.125rem', { lineHeight: '1.5rem' }],
      xl: ['1.25rem', { lineHeight: '1.5rem' }],
      '2xl': ['1.5rem', { lineHeight: '1.75rem' }],
      '3xl': ['2rem', { lineHeight: '2rem' }],
      '4xl': ['2.5rem', { lineHeight: '2.25rem' }],
      '5xl': ['3.5rem', { lineHeight: '1' }],
      '6xl': ['4rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
    },
    fontSize: {
      '3xs': '0.75rem',
      '2xs': '0.8125rem',
      xs: '0.875rem',
      sm: '0.9375rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '2rem',
      '4xl': '2.5rem',
      '5xl': '3.5rem',
      '6xl': '4rem',
      '7xl': '4.5rem',
      '8xl': '6rem',
    },
    extend: {
      borderRadius: {
        none: '0',
        px: '1px',
        sm: '0.125rem',
        default: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2.5rem',
        '5xl': '5rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        light: '0 4px 8px rgba(0,0,0,0.12)',
        default: '0 4px 8px rgba(0,0,0,0.24)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        xl: '0 16px 104px 0 rgba(0,0,0,0.24)',
        'xl-light': '0 16px 104px 0 rgba(0,0,0,0.12)',
        '2xl': '0 40px 104px 0 rgba(0,0,0,0.24)',
        '2xl-light': '0 40px 104px 0 rgba(0,0,0,0.12)',
        inner: 'inset 0 4px 8px 0 rgba(0, 0, 0, 0.32)',
        outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
        none: 'none',
        'blue-light': '0 0 24px 4px #83E2FF',
        'pink': '0 0 24px 4px #c459e5',
        'fire': '0 0 24px 4px #f7685a',
        'purple': '0 0 24px 4px #5f6fe6',
      },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        black: '#000',
        white: '#fff',
        'gray-extra-dark': '#111',
        'gray-darker': '#222',
        'gray-dark': '#333',
        'gray-medium': '#bcbdcc',
        'gray-medium-light': '#dfe0de',
        'gray-light': '#9698a3',
        'gray-extra-light': '#ecedeb',
        'gray-extra-extra-light': '#f7f7f7',
        'pink-bright': '#f75aa6',
        'pink-extra-bright': '#c226cb',
        pink: '#c459e5',
        'pink-light': '#e799ff',
        purple: '#5f6fe6',
        'purple-dark': '#5462cc',
        'purple-darker': '#434ea3',
        'purple-light': '#99a5ff',
        teal: '#61caea',
        fire: '#f7685a',
        'fire-light': '#ff8f85',
        red: '#ff0000',
        blue: '#61caea',
        'blue-light': '#83e2ff',
        'blue-gray': '#9fb5cd',
        green: '#15cd8d',
        'green-light': '#44e3ac',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        'heading': [
          'Work Sans',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      opacity: {
        8: '0.08',
      }
    }
  },
  variants: {
    extend: {}
  },
  plugins: [
    require('@tailwindcss/forms'),
  ]
}
